# Generated by Django 3.2 on 2022-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_file',
            field=models.FileField(blank=True, null=True, upload_to='songs'),
        ),
    ]
