# Generated by Django 3.2 on 2022-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_song_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='create_genre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
