# Generated by Django 3.2 on 2022-04-20 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20220419_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='choose_genre',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='music.genre'),
            preserve_default=False,
        ),
    ]
