# Generated by Django 3.2 on 2022-04-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_alter_album_choose_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='create_genre',
        ),
    ]
