# Generated by Django 3.2 on 2022-04-19 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220409_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='email',
        ),
        migrations.AlterField(
            model_name='message',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
