# Generated by Django 3.2 on 2022-10-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20221012_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
