# Generated by Django 3.2 on 2022-10-20 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_profile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
